
apiVersion: v1
kind: Secret
data:
  mysql_password:  bWFpbW91bmE=
  wordpress_db_password: YmVsbGFiYWg=
  mysql_random_root_password: YmVsbGViYWg=


metadata:
  name: wordpress-secret
  namespace: wordpress
  labels:
    app: wordpress
    env: production
    team: devops
    release: v1.0
type: Opaque   
